name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 30
          plugin_skyline_quality: 1
